### ISSUE TITLE
Non-existent skins.

### ISSUE THREAD

**Issue by darthbhyrava** [polybuildr/petroglyph#29]
In the documentation, it was mentioned that the skins 'monogreen', 'monopurple', 'monored' and 'monoblue' are included by default, and can used via the '--skin SKIN' extension to 'petroglyph init'.

However, the glyph (can I call it 'the glyph' :P) throws up a 'Skin doesn't exist. Exiting' error for all skins except 'monoblue'.
Please look into it. -_-

**Comment by polybuildr** [comment]
Oops. Good catch! I removed them in 874c08e5. The documentation needs to be fixed.
