### ISSUE TITLE
Support for reST

### ISSUE THREAD

**Issue by ParthKolekar** [polybuildr/petroglyph#9]
# reST (Restructured Text)

It well defined and flexible file format for textual data used primarily in the Python programming language community for technical documentation. 

The python docutils also support conversion to HTML natively. 

If possible, could there be a reST in petroglyph?

**Comment by polybuildr** [comment]
I agree, petroglyph should support ReST. Will explore options and add support.

**Comment by polybuildr** [comment]
@ParthKolekar, I'm not too familiar with reStructuredText, could you please review the pull request and let me know if that works for you?
